export { HomePage } from './home'
export { AwakeningConfigPage } from './awakening-config'
export { SimulationPage } from './simulation'
export { StrategyFinderPage } from './strategy-finder'
export { SettingsPage } from './settings'
